/**
 * The Open Relic Workers binding mirrors the Artifacts types generated by the
 * pinned `@cloudflare/workers-types` release. They live in a module as well as
 * in Workers' global namespace so consumers can name their environment without
 * depending on ambient declarations in shared code.
 */

export interface ArtifactsRepoInfo {
  readonly id: string;
  readonly name: string;
  readonly description: string | null;
  readonly defaultBranch: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly lastPushAt: string | null;
  readonly source: string | null;
  readonly readOnly: boolean;
  readonly remote: string;
}

export interface ArtifactsCreateRepoResult {
  readonly id: string;
  readonly name: string;
  readonly description: string | null;
  readonly defaultBranch: string;
  readonly remote: string;
  readonly token: string;
  readonly tokenExpiresAt: string;
}

export interface ArtifactsRepoListResult {
  readonly repos: readonly Omit<ArtifactsRepoInfo, "remote">[];
  readonly total: number;
  readonly cursor?: string;
}

export type ArtifactsTokenScope = "read" | "write";

export interface ArtifactsCreateTokenResult {
  readonly id: string;
  readonly plaintext: string;
  readonly scope: ArtifactsTokenScope;
  readonly expiresAt: string;
}

export interface ArtifactsTokenInfo {
  readonly id: string;
  readonly scope: ArtifactsTokenScope;
  readonly state: "active" | "expired" | "revoked";
  readonly createdAt: string;
  readonly expiresAt: string;
}

export interface ArtifactsTokenListResult {
  readonly tokens: readonly ArtifactsTokenInfo[];
  readonly total: number;
}

export interface ArtifactsRepo extends ArtifactsRepoInfo {
  createToken(scope?: ArtifactsTokenScope, ttl?: number): Promise<ArtifactsCreateTokenResult>;
  listTokens(): Promise<ArtifactsTokenListResult>;
  revokeToken(tokenOrId: string): Promise<boolean>;
  fork(
    name: string,
    opts?: {
      description?: string;
      readOnly?: boolean;
      defaultBranchOnly?: boolean;
    },
  ): Promise<ArtifactsCreateRepoResult>;
}

export type ArtifactsErrorCode =
  | "ALREADY_EXISTS"
  | "NOT_FOUND"
  | "IMPORT_IN_PROGRESS"
  | "FORK_IN_PROGRESS"
  | "INVALID_INPUT"
  | "INVALID_REPO_NAME"
  | "INVALID_TTL"
  | "INVALID_URL"
  | "REMOTE_AUTH_REQUIRED"
  | "UPSTREAM_UNAVAILABLE"
  | "MEMORY_LIMIT"
  | "INTERNAL_ERROR";

export class ArtifactsError extends Error {
  override readonly name = "ArtifactsError";

  constructor(
    readonly code: ArtifactsErrorCode,
    readonly numericCode: number,
    message: string,
  ) {
    super(message);
  }
}

export interface Artifacts {
  create(
    name: string,
    opts?: {
      readOnly?: boolean;
      description?: string;
      setDefaultBranch?: string;
    },
  ): Promise<ArtifactsCreateRepoResult>;
  get(name: string): Promise<ArtifactsRepo>;
  import(params: {
    source: { url: string; branch?: string; depth?: number };
    target: {
      name: string;
      opts?: { description?: string; readOnly?: boolean };
    };
  }): Promise<ArtifactsCreateRepoResult>;
  list(opts?: { limit?: number; cursor?: string }): Promise<ArtifactsRepoListResult>;
  delete(name: string): Promise<boolean>;
}

/** Trusted configuration attached to a custom Worker service binding. */
export interface ArtifactsBindingProps {
  readonly namespace: string;
  readonly publicUrl: string;
}

export type ArtifactsBindingRequest =
  | {
      readonly operation: "create";
      readonly name: string;
      readonly options?: {
        readonly readOnly?: boolean;
        readonly description?: string;
        readonly setDefaultBranch?: string;
      };
    }
  | { readonly operation: "get"; readonly name: string }
  | {
      readonly operation: "import";
      readonly params: {
        readonly source: {
          readonly url: string;
          readonly branch?: string;
          readonly depth?: number;
        };
        readonly target: {
          readonly name: string;
          readonly opts?: { readonly description?: string; readonly readOnly?: boolean };
        };
      };
    }
  | {
      readonly operation: "list";
      readonly options?: { readonly limit?: number; readonly cursor?: string };
    }
  | { readonly operation: "delete"; readonly name: string }
  | {
      readonly operation: "createToken";
      readonly repository: string;
      readonly scope?: ArtifactsTokenScope;
      readonly ttl?: number;
    }
  | { readonly operation: "listTokens"; readonly repository: string }
  | {
      readonly operation: "revokeToken";
      readonly repository: string;
      readonly tokenOrId: string;
    }
  | {
      readonly operation: "fork";
      readonly repository: string;
      readonly name: string;
      readonly options?: {
        readonly description?: string;
        readonly readOnly?: boolean;
        readonly defaultBranchOnly?: boolean;
      };
    };

export type ArtifactsBindingValue =
  | ArtifactsCreateRepoResult
  | ArtifactsRepoInfo
  | ArtifactsRepoListResult
  | ArtifactsCreateTokenResult
  | ArtifactsTokenListResult
  | boolean;

export type ArtifactsBindingResult =
  | { readonly ok: true; readonly value: ArtifactsBindingValue }
  | {
      readonly ok: false;
      readonly error: {
        readonly code: ArtifactsErrorCode;
        readonly numericCode: number;
        readonly message: string;
      };
    };

export interface ArtifactsBindingTransport {
  invoke(request: ArtifactsBindingRequest): Promise<ArtifactsBindingResult>;
}

/** Unscoped installation transport used by the Alchemy namespace adapter. */
export interface InstallationBindingTransport {
  invoke(input: {
    readonly props: ArtifactsBindingProps;
    readonly request: ArtifactsBindingRequest;
  }): Promise<ArtifactsBindingResult>;
}

type MutableRequest<Operation extends ArtifactsBindingRequest["operation"]> = {
  -readonly [Key in keyof Extract<ArtifactsBindingRequest, { operation: Operation }>]: Extract<
    ArtifactsBindingRequest,
    { operation: Operation }
  >[Key];
};
type CreateTokenBindingRequest = MutableRequest<"createToken">;
type ForkBindingRequest = MutableRequest<"fork">;
type CreateBindingRequest = MutableRequest<"create">;
type ListBindingRequest = MutableRequest<"list">;

const unwrap = async <T>(
  transport: ArtifactsBindingTransport,
  request: ArtifactsBindingRequest,
): Promise<T> => {
  const result = await transport.invoke(request);
  if (!result.ok) {
    throw new ArtifactsError(result.error.code, result.error.numericCode, result.error.message);
  }
  // SAFETY: each request variant is paired with its documented result type by
  // the typed client methods below; the RPC envelope cannot express that map.
  return result.value as T;
};

/**
 * Reconstruct the local `ArtifactsError` properties Workers RPC omits from
 * thrown errors. Successful calls keep the same API as the raw custom binding.
 */
export const createOpenRelicArtifacts = (transport: ArtifactsBindingTransport): Artifacts => {
  const repo = (info: ArtifactsRepoInfo): ArtifactsRepo => ({
    ...info,
    createToken: (scope, ttl) => {
      const request: CreateTokenBindingRequest = {
        operation: "createToken",
        repository: info.name,
      };
      if (scope !== undefined) request.scope = scope;
      if (ttl !== undefined) request.ttl = ttl;
      return unwrap(transport, request);
    },
    listTokens: () => unwrap(transport, { operation: "listTokens", repository: info.name }),
    revokeToken: (tokenOrId) =>
      unwrap(transport, {
        operation: "revokeToken",
        repository: info.name,
        tokenOrId,
      }),
    fork: (name, options) => {
      const request: ForkBindingRequest = {
        operation: "fork",
        repository: info.name,
        name,
      };
      if (options !== undefined) request.options = options;
      return unwrap(transport, request);
    },
  });

  return {
    create: (name, options) => {
      const request: CreateBindingRequest = {
        operation: "create",
        name,
      };
      if (options !== undefined) request.options = options;
      return unwrap(transport, request);
    },
    get: (name) => unwrap<ArtifactsRepoInfo>(transport, { operation: "get", name }).then(repo),
    import: (params) => unwrap(transport, { operation: "import", params }),
    list: (options) => {
      const request: ListBindingRequest = {
        operation: "list",
      };
      if (options !== undefined) request.options = options;
      return unwrap(transport, request);
    },
    delete: (name) => unwrap(transport, { operation: "delete", name }),
  };
};
